### PR TITLE
Fix custom marionette port when `:profile` is specified

### LINKED ISSUE #118: Running mulltiple instances of firefox with custom profile
Hi. I am unable to run multiple instances of firefox with custom profile. I specified `:profile` option, but then I had this issue: https://github.com/mozilla/geckodriver/issues/1058.

So I've tried to configure marionette port differently for each profile using
`:args-driver ["--marrionete-port" 2821]`

but then I had this issue:
```
ERROR in (test-cases) (support.clj:201)
Uncaught exception, not in assertion.
expected: nil
  actual: clojure.lang.ExceptionInfo: throw+: {:response {:value {:error "unknown error", :message "Process unexpectedly closed with status: 0", :stacktrace "stack backtrace:\n   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e\n   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46\n   2:           0x440ac8 - webdriver::error::WebDriverError::new::ha0fbd6d1a1131b43\n   3:           0x4487ce - geckodriver::marionette::MarionetteHandler::create_connection::hf0532ddb9e159684\n   4:           0x428570 - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193\n   5:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25\n   6:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba\n   7:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:99\n   8:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473\n   9:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:692\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}, :path "session", :payload {:desiredCapabilities {:loggingPrefs {:browser "ALL"}, :moz:firefoxOptions {:args ("-profile" "/tmp/alza-vox/profiles/firefox/1")}}}, :method :post, :type :etaoin/http-error, :port 4444, :host "127.0.0.1", :status 500, :driver {:type :firefox, :host "127.0.0.1", :port 4444, :url "http://127.0.0.1:4444", :locator "xpath", :capabilities {:loggingPrefs {:browser "ALL"}, :moz:firefoxOptions {:args ("-profile" "/tmp/alza-vox/profiles/firefox/1")}}, :args ("geckodriver" "--port" 4444 "--marionette-port" 2828), :env nil, :process #object[java.lang.UNIXProcess 0x3b0ed98a "java.lang.UNIXProcess@3b0ed98a"]}}
 at slingshot.support$stack_trace.invoke (support.clj:201)
    etaoin.client$call.invokeStatic (client.clj:97)
    etaoin.client$call.invoke (client.clj:64)
    etaoin.api$create_session.invokeStatic (api.clj:141)
    etaoin.api$create_session.doInvoke (api.clj:135)
    clojure.lang.RestFn.invoke (RestFn.java:423)
    etaoin.api$connect_driver.invokeStatic (api.clj:2629)
    etaoin.api$connect_driver.doInvoke (api.clj:2606)
    clojure.lang.RestFn.invoke (RestFn.java:423)
    etaoin.api$boot_driver.invokeStatic (api.clj:2666)
    etaoin.api$boot_driver.doInvoke (api.clj:2652)
    clojure.lang.RestFn.invoke (RestFn.java:423)
    clojure.core$partial$fn__4759.invoke (core.clj:2515)
    app.test$eval4893$fn__4894$fn__4895.invoke (test.clj:26)
    clojure.core$map$fn__4785.invoke (core.clj:2644)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.RT.seq (RT.java:521)
    clojure.lang.RT.nthFrom (RT.java:879)
    clojure.lang.RT.nth (RT.java:854)
    app.test$fn__4907.invokeStatic (test.clj:40)
    app.test/fn (test.clj:36)
    clojure.test$test_var$fn__7983.invoke (test.clj:716)
    clojure.test$test_var.invokeStatic (test.clj:716)
    clojure.test$test_var.invoke (test.clj:707)
    clojure.test$test_vars$fn__8005$fn__8010.invoke (test.clj:734)
    clojure.test$default_fixture.invokeStatic (test.clj:686)
    clojure.test$default_fixture.invoke (test.clj:682)
    clojure.test$test_vars$fn__8005.invoke (test.clj:734)
    app.test$eval4893$fn__4894.invoke (test.clj:32)
    clojure.test$compose_fixtures$fn__7977$fn__7978.invoke (test.clj:693)
    clojure.test$default_fixture.invokeStatic (test.clj:686)
    clojure.test$default_fixture.invoke (test.clj:682)
    clojure.test$compose_fixtures$fn__7977.invoke (test.clj:693)
    clojure.test$test_vars.invokeStatic (test.clj:730)
    clojure.test$test_all_vars.invokeStatic (test.clj:736)
    clojure.test$test_ns.invokeStatic (test.clj:757)
    clojure.test$test_ns.invoke (test.clj:742)
    user$eval85$fn__136.invoke (form-init4168321581349605179.clj:1)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.injected$compose_hooks$fn__19.doInvoke (form-init4168321581349605179.clj:1)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.injected$run_hooks.invokeStatic (form-init4168321581349605179.clj:1)
    leiningen.core.injected$run_hooks.invoke (form-init4168321581349605179.clj:1)
    leiningen.core.injected$prepare_for_hooks$fn__24$fn__25.doInvoke (form-init4168321581349605179.clj:1)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$map$fn__4785.invoke (core.clj:2646)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.boundedLength (RT.java:1749)
    clojure.lang.RestFn.applyTo (RestFn.java:130)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.test$run_tests.invokeStatic (test.clj:767)
    clojure.test$run_tests.doInvoke (test.clj:767)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.core$apply.invoke (core.clj:641)
    user$eval85$fn__148$fn__179.invoke (form-init4168321581349605179.clj:1)
    user$eval85$fn__148$fn__149.invoke (form-init4168321581349605179.clj:1)
    user$eval85$fn__148.invoke (form-init4168321581349605179.clj:1)
    user$eval85.invokeStatic (form-init4168321581349605179.clj:1)
    user$eval85.invoke (form-init4168321581349605179.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6927)
    clojure.lang.Compiler.eval (Compiler.java:6917)
    clojure.lang.Compiler.load (Compiler.java:7379)
    clojure.lang.Compiler.loadFile (Compiler.java:7317)
    clojure.main$load_script.invokeStatic (main.clj:275)
    clojure.main$init_opt.invokeStatic (main.clj:277)
    clojure.main$init_opt.invoke (main.clj:277)
    clojure.main$initialize.invokeStatic (main.clj:308)
    clojure.main$null_opt.invokeStatic (main.clj:342)
    clojure.main$null_opt.invoke (main.clj:339)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```

and browser didn't start at all.

When I was monitoring running geckodriver processes:
```
while true; do ps -aux | grep geckodriver; sleep 1; done
```

I couldn't see the driver there. When running without the `--marionette-port` option though, I could see geckodriver there:
```
user 25199  0.0  0.0  48824 12996 pts/12   Sl+  10:50   0:00 geckodriver --port 4444 --marionette-port 2828
```

so there is probably issue with executing `geckodriver` binary but `etaoin` won't notice it and suppresses the error message?

I configured the port for firefox profile properly:
```
grep -r 2821 /tmp/project/profiles/firefox/1/prefs.js 
user_pref("marionette.port", 2821);
```

### PR DESCRIPTION
**Pull request by nenadalm**
- fixes #118

### CODE REVIEW

File: test/etaoin/api_test2.clj [hunk 1]
```diff
@@ -0,0 +1,24 @@
+(ns etaoin.api-test2
```
Comment (nenadalm) [inline test/etaoin/api_test2.clj]: not the best name I guess but I don't know if it's possible to somehow exclude the test from fixtures: https://github.com/igrishaev/etaoin/blob/3dc31aa2fc4a09056945eb29e35d42fb12799604/test/etaoin/api_test.clj#L33

Comment (nenadalm) [reply test/etaoin/api_test2.clj]: Maybe tests from `api_test.clj` should be moved to something like `functional_test.clj` and thests from `api_test2.clj` should be moved to `api_test.clj`?

**Comment by igrishaev** [comment]
@nenadalm thank your for your contribution! Looks well, I'll brush a couple of details a bit after.
